package com.healthcare_app.api_gateway.entities;

import com.healthcare_app.api_gateway.enums.Role;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a user in the system.
 * Maps to the "app_user" table in the database.
 *
 * Author: B.T.M.A.S.D.B Rathnayaka
 * Date: 2024/07/29
 */
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@Entity
@Table(name = "app_user")
public class User {

    /**
     * The unique identifier of the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user's first name.
     * This field is required and cannot be null.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * The user's last name.
     * This field is required and cannot be null.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * The login identifier for the user (e.g., username or email).
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String login;

    /**
     * The password for the user.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String password;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;
}
