spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/healthcare-app
  logging:
    level:
      root: INFO
      org.springframework.data.mongodb: DEBUG
      com.mongodb: DEBUG

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8086


