spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare-app
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet


server:
  port: 9000

patient-service:
  base:
    url: http://localhost:8080

admin:
  login: "admin@example.com"
  password: "StrongPassword123"
  role: "admin"

logging:
  level:
    org.springframework.security: DEBUG


