spring:
  application:
    name: medicalrecords-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/healthcare-app
  logging:
    level:
      root: INFO
      org.springframework.data.mongodb: DEBUG
      com.mongodb: DEBUG

server:
  port: 8084


