package com.healthcare_app.billing_service.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Represents a bill entity in the healthcare management system.
 * This entity is mapped to the "Bill_table" database table.
 * Uses JPA annotations for ORM and Jakarta Bean Validation annotations for input validation.
 *  * Author: A.A.M.C Abesinghe
 *  * Date: 2024/09/02
 */



@Entity
@Table(name = "bills")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Bill {

    /**
     * The unique identifier for each bill.
     * Automatically generated by the database.
     */



    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The ID of the patient associated with the bill.
     * This field is mandatory.
     */

    @NotNull(message = "Patient ID is mandatory")
    private Long patientId;

    /**
     * The total amount of the bill.
     * This field is mandatory.
     */

    @NotNull(message = "Amount is mandatory")
    private Double amount;

    /**
     * The status of the bill (e.g., "Paid", "Pending").
     * This field is mandatory.
     */

    @NotNull(message = "Status is mandatory")
    private String status;

    /**
     * A list of payments associated with this bill.
     * Uses CascadeType.ALL to cascade all operations and orphan removal to delete orphaned payments.
     */

    @OneToMany(mappedBy = "bill", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<Payment> payments;
}
