package com.healthcare_app.billing_service.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a payment entity in the healthcare management system.
 * This entity is mapped to the "payment_table" database table.
 * Uses JPA annotations for ORM and Jakarta Bean Validation annotations for input validation.
 *  * Author: A.A.M.C Abesinghe
 *  * Date: 2024/09/02
 */


@Entity
@Table(name = "payments")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Payment {

    /**
     * The unique identifier for each payment.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId;

    /**
     * The bill associated with this payment.
     * This is a many-to-one relationship with the Bill entity.
     * Mapped by the "bill_id" foreign key column in the "payments" table.
     * Uses JsonBackReference to prevent infinite recursion during serialization.
     */

    @ManyToOne
    @JoinColumn(name = "bill_id", nullable = false)
    @JsonBackReference
    private Bill bill;

    /**
     * The amount paid.
     * This field is mandatory.
     */

    @NotNull(message = "Amount is mandatory")
    private Double amount;

    /**
     * The date of the payment.
     * This field is mandatory.
     */

    @NotNull(message = "Payment date is mandatory")
    private String paymentDate;
 }
