package com.healthcare_app.medicalrecords_service.model;

import org.springframework.data.annotation.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * This class represents the MedicalRecords entity.
 * It maps to the "medical_records" collection in the MongoDB database.
 *  * Author: P.K.N. Dharmasena
 *  * Date: 2024/07/27
 */
@Document(collection = "medical_records")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class MedicalRecords {

    /**
     * The unique identifier for each medical record.
     * This field is automatically generated by MongoDB.
     */
    @Id
    private String recordId;

    /**
     * The unique identifier of the patient associated with this medical record.
     * This field is mandatory and cannot be null.
     */
    @NotNull(message = "Patient ID is mandatory")
    @Field("patient_id")
    private Long patientId;

    /**
     * The medical history of the patient.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Medical history is mandatory")
    @Field("medical_history")
    private String medicalHistory;

    /**
     * The diagnosis of the patient's condition.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Diagnosis is mandatory")
    private String diagnosis;

    /**
     * The treatments provided to the patient.
     * This field is mandatory and cannot be blank.
     */
    @NotBlank(message = "Treatments are mandatory")
    private String treatments;
}
